# -*- coding: utf-8 -*-
"""Password manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlRIt-rM382KZqbvZ-s08hZdXZ_Xl0Qw
"""

passwords = {}
print("--Welcome to Password Manager--")

def main():
  while True:
    print(" ")
    print("1. Add account")
    print("2. View all accounts")
    print("3. Search account")
    print("4. Delete accont")
    print("5. Exit")
    print(" ")

    choice = int(input("Enter your choice: "))
    if choice == 1:
        add_account()
    elif choice == 2:
        view_acc()
    elif choice == 3:
        search_acc()
    elif choice == 4:
        delete_acc()
    elif choice == 5:
      break
    else:
      print ("You entered a wrong choice! Try again")
      print(" ")
      print(" ")


def add_account():
  acc= input("Enter the account name that you wanna enter: ")
  password = input("Enter the password: ")
  passwords[acc] = password


def view_acc():
  for acc, password in passwords.items():
    print(acc, ":", password)


def search_acc():
  search = input("Enter you account name to search for password: ")

  if search in passwords:
    print("The password for", search, "is", passwords[search])
  else:
    print("wrong account name")



def delete_acc():
  acc = input("Enter the account name that you wanna delete: ")
  if acc in passwords:
    del passwords[acc]
    print ("The account has been deleted!")
  else:
    print("Account not found")

main()