# -*- coding: utf-8 -*-
"""To_do_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0Jfo1_n65PhtQNSl3aK6O4jmiL1BRud
"""

print("--To do list--")
print(" ")
print("Welcome to the to do list app")
tasks = []
def main():
  while True:
    print(" ")
    print(" ")
    print("1. Enter a new task")
    print("2. Remove a task")
    print("3. Display all the tasks")
    print("4. Mark task as completed")
    print("5. Exti")
    print(" ")
    print(" ")

    choice = int(input("Enter your choice: "))
    if choice == 1:
      add_task()
    elif choice == 2:
      remove_task()
    elif choice == 3:
      display_task()
    elif choice == 4:
      completed()
    elif choice == 5:
      break
    else:
      print ("You entered a wrong choice! Try again")
      print(" ")
      print(" ")



def display_task():
  global tasks
  if tasks == []:
    print("There are no tasks yet")
  else:
    for count, task in enumerate(tasks) :
      print(count,".", task)
  print(" ")


def add_task():
  print(" ")
  new_task = input("Enter your new task: ")
  tasks.append(new_task)


def remove_task():
  print(" ")
  task= int(input("Enter the index of the task you want to remove: (starts from 0) "))
  if task < 0 or task >= len(tasks):
    print("The task doesnt exit")
  else:
    del tasks[task]
    print(" ")
    print("Your task has been removed")
    print("Updated tasks: ")
    for count, task in enumerate(tasks) :
      print(count,".", task)

    print(" ")


def completed():
  global tasks
  task = int(input("Enter the task index that you want to complete: "))
  if task < 0 or task >= len(tasks):
    print("The task doesnt exit")
  else:
    completed_task = "[Done]" + tasks[task]
    tasks[task] = completed_task
    print(tasks[task])


main()